# COMP 895   Data Analytics Methods and Techniques
## Spring 2018    Assignment 3

The following are excises you should do using Jupyter Notebook. Export a copy of the notebook and upload it to BlackBoard.<br> _(File Menu ->Download As->Notebook(.ipynb))_<br>  Solutions should be single lines of Python code unless it is otherwise stated. 

Define a 3 × 3 “matrix” a with 

In [2]:
from numpy import *
a = array([[3, 1, 5], [6, 8, 3], [2, 5, 7]])
a

array([[3, 1, 5],
       [6, 8, 3],
       [2, 5, 7]])

`Find the sum of the rows of a. 
This should return:
     array([ 9, 17, 14])`

In [27]:
# your code here



```Filter out the rows of a whose sum is not greater than 10.  Use the functional-programming filter() function.  You’ll have to apply row_stack() to the result (a list of the rows as separate arrays that make it through the filter).  This returns:```

`array([[6, 8, 3],
       [2, 5, 7]])`

In [6]:
# type your code here



`Define a 4 × 4 × 3 array b with `


In [3]:
b = arange(64).reshape(4,4,4)

`This is pictured as a cube with “edges” of length 4, each corresponding to the sequence of indices (0, 1, 2, 3).  It prints out as `

In [ ]:
# execute this cell to print out b
print (b)



`The front upper left of this cube is a sub-cube with indices :
(0, 1) × (0, 1) × (0, 1) while the back lower right is a sub-cube
with indices (2, 3) × (2, 3) × (2, 3).`

### Now, add the back lower right sub-cube element-wise to the front upper left sub-cube.
`(For example, looking at two of the corners, b[2,2,2] is added to b[0.0.0], and b[3,3,3] is added to b[1,1,1].)  Use slices.  The following is how the result is printed.  The elements in bold are the ones that have been updated, and the underlined ones are the ones that have been added to the others.` 


In [17]:
# Write code for adding the back lower right sub-cube element wise
#  to the front upper-left sub-cube here



[ [ [**42 44**  2  3]<br>
    [**50 52**  6  7]<br>
    [ 8  9 10 11]<br>
    [12 13 14 15] ]<br>
<br>
  [ [**74 76** 18 19]<br>
    [**82 84** 22 23]<br>
    [24 25 26 27]<br>
    [28 29 30 31] ]<br>
<br>
  [ [32 33 34 35]<br>
   [36 37 38 39]<br>
   [40 41 42 43]<br>
   [44 45 46 47] ]<br>
<br>
 [ [48 49 50 51]<br>
   [52 53 54 55]<br>
   [56 57 58 59]<br>
   [60 61 62 63] ] ]<br>



In [ ]:
# Define a 3 × 3 “matrix” c as follows (where we also print it).
# execute this block
c = arange(9).reshape(3,3)
print (c)


It’s easy to loop over the rows of **c**.  You’re to iterate over the
columns, printing out each column and (on the same line) the sum of its elements.  (Do this with two lines: a for and a print.)  
The following is the output. 

```
[0 3 6] 9
[1 4 7] 12
[2 5 8] 15

```

In [23]:
# Type your code here



Now, convert c to the corresponding one-dimensional array in FORTRAN order.  The output is :<br>
```
array([0, 3, 6, 1, 4, 7, 2, 5, 8])
```

In [26]:
# Type your code for converting c to a one-dimensional array here



From c, produce an array identical to c except that the first row is moved to the bottom (i.e., new rows at indices 0, 1, 2 correspond to old rows 1, 2, 0).  The following is the result:

```
array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])
```


In [28]:
# Type your code for moving the row in C here



From c, produce an array identical to c except that the first column is moved to the end (i.e., new columns at indices 0, 1, 2 correspond to old columns 1, 2, 0).  The following is the result:
```
array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])
```


In [ ]:
# Create the 4 × 4 array d as follows.
d = arange(16).reshape(4,4)
print (d)


From d, create two 4 × 2 arrays d1, with the first two columns of d, and d2, with the last two columns of d.  They should appear thus:
```
>>> print d1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
>>> print d2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
```

In [29]:
# Type code for creating d1 and d2, and print d1 & d2 here



Next, from d, create two 2 × 4 arrays d1, with the first two rows of d, and d2, with the last two rows of d.  Thus :
```
>>> print d1
[[0 1 2 3]
 [4 5 6 7]]
>>> print d2
[[ 8  9 10 11]
 [12 13 14 15]]
```

In [30]:
# Type code for creating the new d1 and d2, and print d1 & d2 here



In [ ]:
# Define arrays  a1  and   b1   as follows:
a1 = arange(6, 21)
print (a1)

b1 = array([2, 3, 5])
print (b1)

In [32]:
# Now, Form the 15 × 3 array c1 such that c[i,j] is a1[i] mod b1[j]:
# Write your code here



It should look ilke: 
```
>>> print c1
[[0 0 1]
 [1 1 2]
 [0 2 3]
 [1 0 4]
 [0 1 0]
 [1 2 1]
 [0 0 2]
 [1 1 3]
 [0 2 4]
 [1 0 0]
 [0 1 1]
 [1 2 2]
 [0 0 3]
 [1 1 4]
 [0 2 0]]
```

Next, form the array of size 15 whose element at index i is the product of the elements in row i of c1.  (So the element at index i in this array is nonzero iff a1[i] is prime.). 

In [ ]:
# Write your code for this here
#


The answer is:
```
array([0, 2, 0, 0, 0, 2, 0, 3, 0, 0, 0, 4, 0, 4, 0])
```



Now Using NumPy matrices, find the product of :
\begin{bmatrix}
   2 & 3 \\
   0 & 2  
\end{bmatrix}
<br>
and the inverse of :
\begin{bmatrix}
   1 & 2 \\
   3 & 1  
\end{bmatrix}

In [10]:
# Write your code here
#

The answer should be:
```
matrix([[ 1.4,  0.2],
        [ 1.2, -0.4]])
```

Solve the following system of linear equations:
    
 5x<sub>1</sub> –  x<sub>2</sub> + 2x<sub>3</sub> = 7 <br>
-2x<sub>1</sub> + 6x<sub>2</sub> + 9x<sub>3</sub> = 0 <Br>
-7x<sub>1</sub> + 5x<sub>2</sub> – 3x<sub>3</sub> = 7  <br>
    <br>
    (This will take several lines.) 

In [35]:
# Write your code for solving here
#


The answer is:
```    
>>> print x
[ 3.23076923  4.53846154 -2.30769231]
```

You can check this answer by finding A<sup>-1</sup>**b**. 
